/**
 * Backup service — manages manual SQLite backups using
 * better-sqlite3's .backup() API for WAL-safe snapshots.
 */

import fs from 'node:fs';
import path from 'node:path';
import { app } from 'electron';
import { getDb } from '../db/index';
import { createLogger, consoleTransport, metrics } from '@sekel/observability';

const log = createLogger({ module: 'backup', transports: [consoleTransport] });

export interface BackupInfo {
    filename: string;
    filePath: string;
    timestamp: string;
    sizeBytes: number;
}

/** Returns the directory where backups are stored. */
export function getBackupDir(): string {
    return path.join(app.getPath('userData'), 'backups');
}

/** Ensures the backup directory exists. */
function ensureBackupDir(): void {
    const dir = getBackupDir();
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

/** Generates a timestamped backup filename. */
function makeBackupFilename(): string {
    const now = new Date();
    const ts = now.toISOString().replace(/[:.]/g, '-');
    return `sekel-backup-${ts}.db`;
}

/**
 * Creates a backup of the current database using better-sqlite3's .backup() API.
 * This is safe to call while the database is in WAL mode and actively in use.
 *
 * @returns Info about the created backup, or null if backup failed.
 */
export async function createBackup(): Promise<BackupInfo | null> {
    try {
        ensureBackupDir();
        const filename = makeBackupFilename();
        const destPath = path.join(getBackupDir(), filename);

        const db = getDb();
        await db.backup(destPath);

        const stat = fs.statSync(destPath);
        const info: BackupInfo = {
            filename,
            filePath: destPath,
            timestamp: new Date().toISOString(),
            sizeBytes: stat.size,
        };

        log.info('Backup created', { filename, size: formatBytes(stat.size) });
        metrics.increment('backup.created_total');
        return info;
    } catch (err) {
        log.error('Failed to create backup', { error: err instanceof Error ? err.message : String(err) });
        return null;
    }
}

/** Lists all available backups sorted newest first. */
export function listBackups(): BackupInfo[] {
    const dir = getBackupDir();
    if (!fs.existsSync(dir)) return [];

    return fs.readdirSync(dir)
        .filter((f) => f.startsWith('sekel-backup-') && f.endsWith('.db'))
        .map((filename) => {
            const filePath = path.join(dir, filename);
            const stat = fs.statSync(filePath);

            return {
                filename,
                filePath,
                timestamp: stat.mtime.toISOString(),
                sizeBytes: stat.size,
            };
        })
        .sort((a, b) => b.timestamp.localeCompare(a.timestamp));
}

/** Matches the filenames generated by makeBackupFilename(). */
const BACKUP_FILENAME_RE = /^sekel-backup-\d{4}-\d{2}-\d{2}T[\d-]+Z\.db$/;

/** Deletes a specific backup file. */
export function deleteBackup(filename: string): boolean {
    if (!BACKUP_FILENAME_RE.test(filename)) {
        log.warn('Rejected invalid backup filename', { filename });
        return false;
    }

    const backupDir = getBackupDir();
    const resolved = path.resolve(path.join(backupDir, filename));
    if (!resolved.startsWith(backupDir + path.sep)) {
        log.warn('Blocked path escape attempt', { resolved });
        return false;
    }

    if (!fs.existsSync(resolved)) return false;
    fs.unlinkSync(resolved);
    log.info('Backup deleted', { filename });
    return true;
}

/** Returns the total size of all backups. */
export function getBackupsTotalSize(): number {
    return listBackups().reduce((sum, b) => sum + b.sizeBytes, 0);
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function formatBytes(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
